-- 특정 기간동안 대여 가능한 자동차들의 대여비용 구하기
-- 프로그래머스 심화 (⭐⭐⭐⭐⭐)
-- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/157339
-- 작성자: 김하연
-- 작성일: 2026. 07. 28. 03:59:50

-- 코드를 입력하세요
SELECT C.CAR_ID, C.CAR_TYPE, ROUND(C.DAILY_FEE * 30 * (1-D.DISCOUNT_RATE/100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
ON C.CAR_TYPE = D.CAR_TYPE AND D.DURATION_TYPE = '30일 이상'
WHERE C.CAR_TYPE IN ('세단','SUV')
AND C.CAR_ID NOT IN (
      SELECT CAR_ID 
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
      WHERE END_DATE >= '2022-11-01' AND START_DATE <= '2022-11-30'
  )
GROUP BY C.CAR_ID
HAVING FEE BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, C.CAR_TYPE, C.CAR_ID DESC